version: '3.8'
services:
  
  userdao_db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        
        
  test_userdao_db:
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql